server:
  port: 8080
  servlet:
    path: /api

# Logg Config.
logging:
  file: logs/oficina.log
  level:
    ROOT: ERROR
    org.springframework.web: DEBUG
    br.com.integralabs.oficina.*: DEBUG

# Spring Async Thread Pool config.
scheduledExecutorService:
  #corePoolSize: 2

spring:
  #Spring Data Repository
  jpa:
    generate-ddl: true
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  # H2
  h2:
    console:
      enabled: true
      path: /h2

  # Datasource
  datasource:
    url: jdbc:h2:file:./h2/oficina;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver