server:
  port: 8080
  servlet:
    path: /api

# Logg Config.
logging:
  file: logs/oficina.log
  level:
    ROOT: ERROR
    org.springframework.web: DEBUG
    br.com.integralabs.oficina.*: DEBUG

# Spring Async Thread Pool config.
scheduledExecutorService:
  #corePoolSize: 2

jdbc:
  url: jdbc:postgresql://localhost:5432/oficina
  username: oficina
  password: oficina
  maxPoolSize: 2

spring:
  jpa:
    generate-ddl: true
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true